AWSTemplateFormatVersion: 2010-09-09

Description: lecture10 RDS

Resources:

  rdssecuritygroup:
   Type: AWS::EC2::SecurityGroup
   Properties: 
    GroupDescription: rds-securitygroup
    SecurityGroupEgress: 
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !ImportValue PublicSecurityGroupID
    VpcId: !ImportValue VPCID

  # RDS
  #
  #
  rdsinstance:  
    Type: AWS::RDS::DBInstance
    Properties: 
     AllocatedStorage: 20
     DBInstanceClass: db.t3.micro
     DBSubnetGroupName: 
        !ImportValue rdssubnetgroup
     Engine: mysql
     EngineVersion: 8.0.28
     MasterUsername: admin
     MasterUserPassword: adminadmin
     StorageType: gp2
     Tags:
      - Key: Name
        Value: rdsinstance
     VPCSecurityGroups:
      - !Ref rdssecuritygroup