AWSTemplateFormatVersion: 2010-09-09
Description: lecture10 alb

Resources:

 alb:
   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
   Properties: 
     IpAddressType: ipv4
     Name: lecture10
     Scheme: internet-facing
     SecurityGroups: 
       - !Ref albSecurityGroup
     SubnetMappings: 
        - SubnetId: !ImportValue WebPublicSubnet1ID
        - SubnetId: !ImportValue WebPublicSubnet2ID
     Type: application
     Tags: 
       - Key: Name
         Value: lecutre10

 albSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties: 
     GroupDescription: lecture10-albSecurityGroup
     VpcId: !ImportValue VPCID
     SecurityGroupIngress: 
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0
         Description: HTTP From AnyWhere         
     Tags: 
       - Key: Name
         Value: lecture10
  
 albTargetGroup:
   Type: AWS::ElasticLoadBalancingV2::TargetGroup
   Properties: 
     VpcId: !ImportValue VPCID
     HealthCheckIntervalSeconds: 30
     HealthCheckEnabled: true
     HealthCheckPath: /
     HealthCheckPort: traffic-port
     HealthCheckProtocol: HTTP
     HealthCheckTimeoutSeconds: 5
     HealthyThresholdCount: 5
     IpAddressType: ipv4
     Port: 80
     Protocol: HTTP
     ProtocolVersion: HTTP1
     TargetType: instance
     Targets: 
         - Id: !ImportValue WebInstanceAlbTargetGroupID
           Port: 80
     UnhealthyThresholdCount: 2
     Matcher: 
        HttpCode: 200
     Tags: 
       - Key: Name
         Value: lecture10 

 Listener:
  Type: AWS::ElasticLoadBalancingV2::Listener
  Properties:
     DefaultActions: 
       - Type: forward
         TargetGroupArn: !Ref albTargetGroup
     LoadBalancerArn: !Ref alb
     Port: 80
     Protocol: HTTP
     