AWSTemplateFormatVersion: 2010-09-09
Description: lecture10 S3

Resources:

 S3:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: lecture10
     PublicAccessBlockConfiguration:
       BlockPublicAcls: True
       BlockPublicPolicy: True
       IgnorePublicAcls: True
       RestrictPublicBuckets: True

 VPCEndpoint:
   Type: AWS::EC2::VPCEndpoint
   Properties:
     RouteTableIds: 
     - !ImportValue RouteTableID
     ServiceName: com.amazonaws.ap-northeast-1.s3
     VpcEndpointType: Gateway
     VpcId: !ImportValue VPCID

