AWSTemplateFormatVersion: 2010-09-09

Description: lecture10 RDS

Resources:

  rdssecuritygroup:
   Type: AWS::EC2::SecurityGroup
   Properties: 
    GroupDescription: rds-securitygroup
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !ImportValue PublicSecurityGroupID
    VpcId: !ImportValue VPCID

  # RDS
  #
  #
  rdsinstance:  
    Type: AWS::RDS::DBInstance
    Properties: 
     AllocatedStorage: 20
     DBInstanceClass: db.t3.micro
     DBSubnetGroupName: 
        !ImportValue RdsSubnetGroupMysqlID
     Engine: mysql
     EngineVersion: "8.0.35"
     MasterUsername: admin
     MasterUserPassword: '{{resolve:ssm-secure:rds-master-user-password:1}}'
     StorageType: gp2
     Tags:
      - Key: Name
        Value: rdsinstance
     VPCSecurityGroups:
      - !Ref rdssecuritygroup
      
      