AWSTemplateFormatVersion: 2010-09-09

Description: lecture10 RDS

Parameters:
# 
# RDSUser
# 
  RDSUser:
    Description: Input RDS Maseter User Name
    Type: String
    Default: root
# 
# RDSpassword
#
  RDSpassword:
    Description: Input RDS Password 
    Type: String
    NoEcho: true

Resources:

  rdssecuritygroup:
   Type: AWS::EC2::SecurityGroup
   Properties: 
    GroupDescription: rds-securitygroup
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !ImportValue PublicSecurityGroupID
    VpcId: !ImportValue VPCID

  # RDS
  #
  #
  rdsinstance:  
    Type: AWS::RDS::DBInstance
    Properties: 
     AllocatedStorage: 20
     DBInstanceClass: db.t3.micro
     DBSubnetGroupName: 
        !ImportValue RdsSubnetGroupMysqlID
     Engine: mysql
     EngineVersion: "8.0.35"
     MasterUsername: !Ref RDSUser
     MasterUserPassword: !Ref RDSpassword
     StorageType: gp2
     Tags:
      - Key: Name
        Value: rdsinstance
     VPCSecurityGroups:
      - !Ref rdssecuritygroup

