AWSTemplateFormatVersion: 2010-09-09

Description: lecture10 RDS

Parameters:
# 
# RDS User Password
# 
 RDSUserPassword:
   Type: String
   Description: rds master user password
   NoEcho: true
   MinLength: 8
   MaxLength: 128
   AllowedPattern: "[a-zA-Z0-9]*"

Resources:

  rdssecuritygroup:
   Type: AWS::EC2::SecurityGroup
   Properties: 
    GroupDescription: rds-securitygroup
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: !ImportValue PublicSecurityGroupID
    VpcId: !ImportValue VPCID

  # RDS
  #
  #
  rdsinstance:  
    Type: AWS::RDS::DBInstance
    Properties: 
     AllocatedStorage: 20
     DBInstanceClass: db.t3.micro
     DBSubnetGroupName: 
        !ImportValue RdsSubnetGroupMysqlID
     Engine: mysql
     EngineVersion: "8.0.35"
     MasterUsername: admin
     MasterUserPassword: !Ref RDSUserPassword
     StorageType: gp2
     Tags:
      - Key: Name
        Value: rdsinstance
     VPCSecurityGroups:
      - !Ref rdssecuritygroup

